### ISSUE TITLE
[FEATURE] Support "image/heic" Image Format

### ISSUE THREAD

**Issue by krisamin** [RouHim/this-week-in-past#110]

**Comment by RouHim** [comment]
Hello krisamin, thank you for your issue.
Sadly I heavily rely on a library called "[image-rc](https://github.com/image-rs)" for decoding images.
As this library does not support HEIC images due to [this open issue](https://github.com/image-rs/image/issues/1375), I also do not support them.

I know that the iPhone produces these images in live mode, but the main problem seems to be that HEIF images are based on a proprietary, closed source codec that can only be used by open source projects with great effort.

**Comment by RPonturo** [comment]
Hello RouHim, why don't you use this library for HEIC?

https://github.com/strukturag/libheif

**Comment by RouHim** [comment]
> Hello RouHim, why don't you use this library for HEIC?
> 
> https://github.com/strukturag/libheif

Because of this: https://github.com/image-rs/image/issues/1375#issuecomment-1675739165
